-- Crop value-chain knowledge base (static reference, NOT live demand).
-- Generated from krishiniti_crop_valuechain_final.csv. Safe to re-run.
CREATE TABLE IF NOT EXISTS crop_value_chain (
  id SERIAL PRIMARY KEY,
  crop_name VARCHAR(100) NOT NULL,
  botanical_name VARCHAR(150),
  plant_part VARCHAR(120) NOT NULL,
  industry VARCHAR(80) NOT NULL,
  product VARCHAR(200) NOT NULL,
  value_level VARCHAR(20) NOT NULL CHECK (value_level IN ('High','Medium','Low')),
  buyer_type VARCHAR(80) NOT NULL,
  processing_required BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE (crop_name, plant_part, industry, product, buyer_type)
);
CREATE INDEX IF NOT EXISTS idx_crop_value_chain_crop ON crop_value_chain (crop_name);

INSERT INTO crop_value_chain (crop_name,botanical_name,plant_part,industry,product,value_level,buyer_type,processing_required) VALUES
('Banana','Musa paradisiaca','Fruit (Ripe)','Food','Banana Puree/Pulp','High','Processor',TRUE),
('Banana','Musa paradisiaca','Fruit (Raw)','Food','Banana Chips','Medium','Manufacturer',TRUE),
('Banana','Musa paradisiaca','Peel','Nutraceutical','Banana Peel Flour','Medium','Processor',TRUE),
('Banana','Musa paradisiaca','Pseudostem','Textile','Banana Fiber','High','Textile Mill',TRUE),
('Banana','Musa paradisiaca','Pseudostem','Packaging','Banana Fiber Packaging Sheets','Medium','Manufacturer',TRUE),
('Banana','Musa paradisiaca','Leaf','Packaging','Banana Leaf (Eco-friendly Plates)','Low','Wholesaler',FALSE),
('Moringa','Moringa oleifera','Leaf','Nutraceutical','Moringa Leaf Powder','High','Exporter',TRUE),
('Moringa','Moringa oleifera','Seed','Essential Oil','Moringa Seed Oil (Ben Oil)','High','Oil Processor',TRUE),
('Moringa','Moringa oleifera','Seed','Pharma','Moringa Seed Extract Capsules','High','Pharma Company',TRUE),
('Moringa','Moringa oleifera','Pod','Food','Fresh Drumstick (Vegetable)','Medium','Wholesaler',FALSE),
('Moringa','Moringa oleifera','Flower','Nutraceutical','Moringa Flower Tea','Medium','Processor',TRUE),
('Moringa','Moringa oleifera','Seed Cake','Animal Feed','Moringa Oil Cake','Low','Feed Company',FALSE),
('Lemon','Citrus limon','Fruit (Juice)','Food','Lemon Juice Concentrate','High','Processor',TRUE),
('Lemon','Citrus limon','Peel','Essential Oil','Lemon Essential Oil','High','Oil Processor',TRUE),
('Lemon','Citrus limon','Peel','Food','Citrus Pectin','Medium','Manufacturer',TRUE),
('Lemon','Citrus limon','Peel','Cosmetics','Lemon Peel Extract','Medium','Manufacturer',TRUE),
('Lemon','Citrus limon','Seed','Pharma','Lemon Seed Oil Extract','Low','Pharma Company',TRUE),
('Lemon','Citrus limon','Fruit (Fresh)','Export','Fresh Lemon','High','Exporter',FALSE),
('Mango','Mangifera indica','Fruit (Ripe Pulp)','Food','Mango Pulp/Puree','High','Processor',TRUE),
('Mango','Mangifera indica','Fruit (Raw)','Food','Mango Pickle','Medium','Manufacturer',TRUE),
('Mango','Mangifera indica','Peel','Nutraceutical','Mango Peel Powder','Medium','Processor',TRUE),
('Mango','Mangifera indica','Kernel','Cosmetics','Mango Kernel Butter','High','Manufacturer',TRUE),
('Mango','Mangifera indica','Kernel','Animal Feed','Mango Kernel Meal','Low','Feed Company',TRUE),
('Mango','Mangifera indica','Fruit (Fresh)','Export','Fresh Mango','High','Exporter',FALSE),
('Coconut','Cocos nucifera','Husk','Textile','Coconut Coir Fiber','High','Textile Mill',TRUE),
('Coconut','Cocos nucifera','Husk','Packaging','Coco Peat (Coir Pith)','Medium','Manufacturer',TRUE),
('Coconut','Cocos nucifera','Kernel (Copra)','Essential Oil','Coconut Oil','High','Oil Processor',TRUE),
('Coconut','Cocos nucifera','Shell','Bioenergy','Coconut Shell Charcoal','Medium','Manufacturer',TRUE),
('Coconut','Cocos nucifera','Water','Food','Packaged Coconut Water','High','Exporter',TRUE),
('Coconut','Cocos nucifera','Kernel','Cosmetics','Virgin Coconut Oil','High','Manufacturer',TRUE),
('Turmeric','Curcuma longa','Rhizome','Food','Turmeric Powder','High','Processor',TRUE),
('Turmeric','Curcuma longa','Rhizome','Pharma','Curcumin Extract','High','Pharma Company',TRUE),
('Turmeric','Curcuma longa','Rhizome','Cosmetics','Turmeric Oleoresin/Extract','Medium','Manufacturer',TRUE),
('Turmeric','Curcuma longa','Rhizome','Export','Dried Turmeric Fingers','High','Exporter',TRUE),
('Turmeric','Curcuma longa','Leaf','Essential Oil','Turmeric Leaf Oil','Low','Oil Processor',TRUE),
('Ginger','Zingiber officinale','Rhizome','Food','Dried Ginger Powder (Sonth)','High','Processor',TRUE),
('Ginger','Zingiber officinale','Rhizome','Essential Oil','Ginger Oil','High','Oil Processor',TRUE),
('Ginger','Zingiber officinale','Rhizome','Pharma','Ginger Oleoresin','High','Pharma Company',TRUE),
('Ginger','Zingiber officinale','Rhizome','Food','Ginger Candy/Preserve','Medium','Manufacturer',TRUE),
('Ginger','Zingiber officinale','Rhizome','Export','Fresh Ginger','Medium','Exporter',FALSE),
('Onion','Allium cepa','Bulb','Food','Dehydrated Onion Flakes/Powder','High','Processor',TRUE),
('Onion','Allium cepa','Bulb','Export','Fresh Onion','High','Exporter',FALSE),
('Onion','Allium cepa','Peel','Nutraceutical','Onion Peel Extract (Quercetin)','Medium','Manufacturer',TRUE),
('Onion','Allium cepa','Bulb','Pharma','Onion Extract Capsules','Low','Pharma Company',TRUE),
('Onion','Allium cepa','Peel','Animal Feed','Onion Peel Meal','Low','Feed Company',FALSE),
('Tomato','Solanum lycopersicum','Fruit','Food','Tomato Puree/Paste','High','Processor',TRUE),
('Tomato','Solanum lycopersicum','Fruit','Food','Tomato Ketchup/Sauce','High','Manufacturer',TRUE),
('Tomato','Solanum lycopersicum','Seed','Essential Oil','Tomato Seed Oil','Medium','Oil Processor',TRUE),
('Tomato','Solanum lycopersicum','Pomace','Animal Feed','Tomato Pomace Meal','Low','Feed Company',FALSE),
('Tomato','Solanum lycopersicum','Peel','Nutraceutical','Lycopene Extract','High','Manufacturer',TRUE),
('Chilli','Capsicum annuum','Fruit (Dried)','Food','Chilli Powder','High','Processor',TRUE),
('Chilli','Capsicum annuum','Fruit','Pharma','Oleoresin Capsicum','High','Pharma Company',TRUE),
('Chilli','Capsicum annuum','Fruit','Export','Dried Whole Chilli','High','Exporter',TRUE),
('Chilli','Capsicum annuum','Seed','Animal Feed','Chilli Seed Meal','Low','Feed Company',FALSE),
('Chilli','Capsicum annuum','Fruit','Cosmetics','Capsaicin Extract','Medium','Manufacturer',TRUE),
('Potato','Solanum tuberosum','Tuber','Food','Potato Starch','High','Processor',TRUE),
('Potato','Solanum tuberosum','Tuber','Food','Potato Chips/Flakes','High','Manufacturer',TRUE),
('Potato','Solanum tuberosum','Tuber','Export','Fresh Potato','Medium','Exporter',FALSE),
('Potato','Solanum tuberosum','Peel','Animal Feed','Potato Peel Meal','Low','Feed Company',FALSE),
('Potato','Solanum tuberosum','Tuber','Bioenergy','Potato Starch-based Bioethanol','Medium','Manufacturer',TRUE),
('Sugarcane','Saccharum officinarum','Stem/Cane','Food','Sugar (Sucrose)','High','Processor',TRUE),
('Sugarcane','Saccharum officinarum','Stem/Cane','Bioenergy','Ethanol','High','Manufacturer',TRUE),
('Sugarcane','Saccharum officinarum','Bagasse','Packaging','Bagasse Pulp Packaging Board','Medium','Manufacturer',TRUE),
('Sugarcane','Saccharum officinarum','Molasses','Food','Jaggery/Molasses','Medium','Processor',TRUE),
('Sugarcane','Saccharum officinarum','Bagasse','Bioenergy','Bagasse-based Cogeneration Power','Low','Manufacturer',TRUE),
('Cotton','Gossypium hirsutum','Lint (Fiber)','Textile','Cotton Yarn/Fabric','High','Textile Mill',TRUE),
('Cotton','Gossypium hirsutum','Seed','Essential Oil','Cottonseed Oil','High','Oil Processor',TRUE),
('Cotton','Gossypium hirsutum','Seed Cake','Animal Feed','Cottonseed Cake','Medium','Feed Company',FALSE),
('Cotton','Gossypium hirsutum','Linters','Pharma','Pharma-grade Cellulose','Medium','Manufacturer',TRUE),
('Cotton','Gossypium hirsutum','Lint','Export','Raw Cotton Bales','High','Exporter',FALSE),
('Groundnut','Arachis hypogaea','Seed (Kernel)','Essential Oil','Groundnut Oil','High','Oil Processor',TRUE),
('Groundnut','Arachis hypogaea','Seed Cake','Animal Feed','Groundnut Oil Cake','Medium','Feed Company',FALSE),
('Groundnut','Arachis hypogaea','Kernel','Food','Roasted/Salted Groundnut','Medium','Manufacturer',TRUE),
('Groundnut','Arachis hypogaea','Shell','Bioenergy','Groundnut Shell Briquettes','Low','Manufacturer',TRUE),
('Groundnut','Arachis hypogaea','Kernel','Export','Fresh/Dried Groundnut','High','Exporter',FALSE),
('Papaya','Carica papaya','Fruit (Ripe)','Food','Papaya Pulp/Puree','Medium','Processor',TRUE),
('Papaya','Carica papaya','Fruit (Raw/Latex)','Pharma','Papain Enzyme','High','Pharma Company',TRUE),
('Papaya','Carica papaya','Seed','Cosmetics','Papaya Seed Oil','Medium','Manufacturer',TRUE),
('Papaya','Carica papaya','Fruit (Ripe)','Export','Fresh Papaya','Medium','Exporter',FALSE),
('Papaya','Carica papaya','Leaf','Nutraceutical','Papaya Leaf Extract','Medium','Processor',TRUE),
('Pomegranate','Punica granatum','Fruit (Arils)','Food','Pomegranate Juice Concentrate','High','Processor',TRUE),
('Pomegranate','Punica granatum','Peel','Nutraceutical','Pomegranate Peel Extract (Punicalagin)','High','Manufacturer',TRUE),
('Pomegranate','Punica granatum','Seed','Essential Oil','Pomegranate Seed Oil','High','Oil Processor',TRUE),
('Pomegranate','Punica granatum','Fruit (Fresh)','Export','Fresh Pomegranate','High','Exporter',FALSE),
('Pomegranate','Punica granatum','Peel','Cosmetics','Pomegranate Peel Extract (Cosmetic Grade)','Medium','Manufacturer',TRUE),
('Guava','Psidium guajava','Fruit (Ripe)','Food','Guava Pulp/Puree','High','Processor',TRUE),
('Guava','Psidium guajava','Leaf','Nutraceutical','Guava Leaf Extract','Medium','Manufacturer',TRUE),
('Guava','Psidium guajava','Fruit','Food','Guava Jam/Jelly','Medium','Manufacturer',TRUE),
('Guava','Psidium guajava','Seed','Essential Oil','Guava Seed Oil','Low','Oil Processor',TRUE),
('Guava','Psidium guajava','Fruit (Fresh)','Export','Fresh Guava','Medium','Exporter',FALSE),
('Garlic','Allium sativum','Bulb','Food','Garlic Powder/Flakes','High','Processor',TRUE),
('Garlic','Allium sativum','Bulb','Pharma','Garlic Extract Capsules (Allicin)','High','Pharma Company',TRUE),
('Garlic','Allium sativum','Bulb','Essential Oil','Garlic Oil','Medium','Oil Processor',TRUE),
('Garlic','Allium sativum','Bulb','Export','Fresh Garlic','Medium','Exporter',FALSE),
('Garlic','Allium sativum','Peel','Animal Feed','Garlic Peel Meal','Low','Feed Company',FALSE),
('Drumstick','Moringa oleifera','Root','Pharma','Moringa Root Extract','Medium','Pharma Company',TRUE),
('Drumstick','Moringa oleifera','Bark','Nutraceutical','Moringa Bark Extract','Low','Manufacturer',TRUE),
('Drumstick','Moringa oleifera','Pod','Food','Dehydrated Drumstick Powder','Medium','Processor',TRUE),
('Drumstick','Moringa oleifera','Gum/Resin','Pharma','Moringa Gum','Low','Pharma Company',TRUE),
('Drumstick','Moringa oleifera','Pod','Export','Fresh Drumstick (Export Grade)','Medium','Exporter',FALSE),
('Coriander','Coriandrum sativum','Seed','Food','Coriander Powder','High','Processor',TRUE),
('Coriander','Coriandrum sativum','Seed','Essential Oil','Coriander Seed Oil','Medium','Oil Processor',TRUE),
('Coriander','Coriandrum sativum','Leaf','Export','Fresh Coriander Leaves','Medium','Exporter',FALSE),
('Coriander','Coriandrum sativum','Seed','Export','Whole Coriander Seed','High','Exporter',TRUE),
('Coriander','Coriandrum sativum','Leaf','Nutraceutical','Coriander Leaf Extract','Low','Manufacturer',TRUE)
ON CONFLICT (crop_name, plant_part, industry, product, buyer_type) DO UPDATE SET
  botanical_name=EXCLUDED.botanical_name, value_level=EXCLUDED.value_level, processing_required=EXCLUDED.processing_required;

-- Public crop-value ranking (no farmer data needed):
CREATE OR REPLACE VIEW crop_value_summary AS
SELECT crop_name,
       COUNT(*) AS channels,
       COUNT(*) FILTER (WHERE value_level='High')   AS high_value,
       COUNT(*) FILTER (WHERE value_level='Medium') AS medium_value,
       COUNT(*) FILTER (WHERE value_level='Low')    AS low_value,
       ROUND(100.0*(3*COUNT(*) FILTER (WHERE value_level='High')
                  + 2*COUNT(*) FILTER (WHERE value_level='Medium')
                  +   COUNT(*) FILTER (WHERE value_level='Low')) / (3*COUNT(*)),0) AS value_score
FROM crop_value_chain GROUP BY crop_name ORDER BY value_score DESC, channels DESC;
